### ISSUE TITLE
Confuse Cluster Labels 

### ISSUE THREAD

**Issue by froger** [octree-gva/Zeitline#9]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report (please search on github for a similar issue before submiting)
[x] feature request
[ ] support request
```
Not sure if it's a bug report or a feature request. I have try the zeitline with lots of data (NYC Flights 2014), and try to play a bit with drag'n drop.

**Current behavior**
When I am moving the intervals, clusters of `99+` get completly collapsed. It looks like it is a big cluster full of `99+`. Also the small clusters are so near one from other than the labels just got confuse.  

**Expected behavior**
I should see the differents clusters, by maybe separate them with a small white line. 

**Minimal reproduction of the problem with instructions**
[Code Pen](https://codepen.io/doublecompil/pen/YQjaaN)

 * **D3 timeline version:** 0.0.2
 * **Browser and environment:** Firefox 54.0.1, Mac OSX 10.11.6

**Comment by froger** [comment]
@cyberschnaps Can you have a look [there ?](https://octree-gva.github.io/Zeitline/docs/examples/heavy-data.html). @BafS just made a cleaner seperation between adjacent clusters, it's far better ;).

We are just waiting your feedbacks for closing this issue.

**Comment by cyberschnaps** [comment]
@froger @BafS sorry for coming back late on this, could you provide a working example for check, the one above leads to documentation. Thanks guys 👍

**Comment by BafS** [comment]
@cyberschnaps The link is the right one but the example was not loading, it should be working now.

**Comment by cyberschnaps** [comment]
Noooooooob here, sorry ^^

So it's indeed better, but we still have this problem of overlapping 99+'s. Are the clusters separated by a min. 2px distance? 

It seems like a lot less (<0px) but maybe it's just a Retina screen thing on my side. 

In order to make things straight we would now have 2 options:
1 — The quickest: augment the minimum distance between clusters and points until the numbers above the dots don't overlap anymore.
2 — The best, but very surely too late to do this at this point: The minimal distance of 2px between clusters should be calculated fro label to label, therefore any label coming too close to another would trigger the clustering of the represented dots. 

@BafS waddaya think?

**Comment by froger** [comment]
Closing this issue, as it has been in stale for a while
